In [4]:
#addition of matrices using numpy

import numpy as np
A=np.array([1,2,3])
B=np.array([4,5,6])
C= A + B

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Addition of A and B:")
print(C)


Matrix A:
[1 2 3]
Matrix B:
[4 5 6]
Addition of A and B:
[5 7 9]
